hospital_management/appointments/urls.py
from django.urls import path
from appointments import views

app_name="appointments"

urlpatterns = [
    path('appointmentbook/', views.book_appointment, name='book_appointment'),
    path('history/', views.appointment_history, name='appointment_history'),
    path('doctor/appointments/', views.doctor_appointments, name='doctor_appointments'),
    path('edit/<int:appointment_id>/', views.edit_appointment, name='edit_appointment'),
    path('delete/<int:appointment_id>/', views.delete_appointment, name='delete_appointment'),



]

hospital_management/doctors/urls.py
from django.urls import path
from doctors import views

app_name="doctors"

urlpatterns = [
    path('',views.alldepartments,name="department"),
    path('doctor/<int:d>',views.alldoctors,name="doctor"),
    path('doctorsdetail/<int:d>',views.doctorsdetails,name="doctorsdetail"),
    path('service/',views.service,name="service"),
    path('adddepartment',views.add_department,name="add_department"),
    path('adddoctor',views.add_doctor,name="add_doctor"),
    path('searchdoctor/', views.search_doctor, name="searchdoctor"),
    path('edit-department/<int:id>/', views.edit_department, name="edit_department"),
    path('delete-department/<int:id>/', views.delete_department, name="delete_department"),


]

hospital_management/hospital_management/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('doctors.urls')),
    path('users/', include('users.urls')),
    path('appointments/', include('appointments.urls')),
    path('pharmacy/', include('pharmacy.urls')),
    path('prescriptions/', include('prescriptions.urls')),


]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

hospital_management/pharmacy/urls.py
from django.urls import path
from pharmacy import views

app_name="pharmacy"

urlpatterns = [
    path('category/', views.allcategories, name='category'),
    path('medicines/<int:m>',views.allmedicines,name="medicines"),
    path('medicinesdetail/<int:m>', views.medicinesdetails, name="medicinesdetail"),
    path('addcat',views.addcategory,name="addcat"),
    path('addmedicine',views.addmedicine,name="addmed"),
    path('addtocart/<int:i>', views.add_to_cart, name="addtocart"),
    path('cartview',views.cart_view,name="cartview"),
    path('cartremove/<int:i>',views.cart_remove,name="cartremove"),
    path('cartdelete/<int:i>',views.cart_delete,name="cartdelete"),
    path('orderform',views.order_form,name="orderform"),
    path('status/<u>',views.payment_status,name="status"),
    path('orderview',views.order_view,name="orderview"),
    path('addstock/<int:m>',views.add_stock,name="addstock"),
    path('search/', views.search_medicine, name="search"),
    path('editcategory/<int:category_id>/', views.edit_category, name='edit_category'),
    path('deletecategory/<int:category_id>/', views.delete_category, name='delete_category'),


]

hospital_management/users/urls.py
from django.urls import path
from users import views

app_name="users"

urlpatterns = [
    path('admin_register/', views.admin_register, name='admin_register'),
    path('doctor_register/', views.doctor_register, name='doctor_register'),
    path('patient_register/', views.patient_register, name='patient_register'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),


]

hospital_management/appointments/models.py
from django.db import models
from doctors.models import Doctor,Department
from patients.models import Patient


class Appointment(models.Model):
    patient = models.ForeignKey(Patient, on_delete=models.CASCADE)
    doctor = models.ForeignKey(Doctor, on_delete=models.CASCADE)
    department = models.ForeignKey(Department, on_delete=models.CASCADE)
    date = models.DateField()
    time = models.TimeField()
    message = models.TextField(blank=True, null=True)
    phone_number = models.CharField(max_length=15, blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    status = models.CharField(
        max_length=50,
        choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Cancelled', 'Cancelled')],
        default='Pending'
    )

    def __str__(self):
        return f"Appointment with {self.doctor.first_name} {self.doctor.last_name} on {self.date} at {self.time}"

hospital_management/doctors/models.py
from django.db import models
from users.models import CustomUser

class Department(models.Model):
    name = models.CharField(max_length=100, unique=True)
    description = models.TextField(blank=True, null=True)
    image = models.ImageField(upload_to="department")

    def __str__(self):
        return self.name

class Doctor(models.Model):
    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE,null=True)
    name = models.CharField(max_length=100, unique=True,blank=True, null=True)
    # password = models.CharField(max_length=150, null=True, blank=True)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    description = models.TextField(blank=True, null=True)
    image = models.ImageField(upload_to="department", blank=True, null=True)
    email = models.EmailField(unique=True)
    phone_number = models.CharField(max_length=15, blank=True, null=True)
    specialization = models.CharField(max_length=100)
    department = models.ForeignKey(Department, on_delete=models.CASCADE, related_name='doctors')
    date_joined = models.DateField(auto_now_add=True)

    def __str__(self):
        return f"Dr. {self.first_name} {self.last_name} - {self.specialization}"

hospital_management/appointments/views.py
from django.shortcuts import render, redirect , get_object_or_404
from appointments.models import Appointment
from doctors.models import Doctor, Department
# from django.contrib.auth.decorators import login_required

def book_appointment(request):

    doctors = Doctor.objects.all()

    if request.method == 'POST':
        department_name = request.POST['d']
        doctor_name = request.POST['doc']
        date = request.POST['date']
        time = request.POST['time']
        name = request.POST['name']
        phone = request.POST['phone']
        message = request.POST['message']

        selected_department = Department.objects.get(name=department_name)
        doc = Doctor.objects.get(id=doctor_name)

        try:
            patient = request.user.patient_profile
        except AttributeError:
            # Handle the case where the user is not a patient
            patient = None

        if patient:
            a = Appointment.objects.create(
                patient=patient,
                date=date,
                time=time,
                phone_number=phone,
                message=message,
                department=selected_department,
                doctor=doc
            )
            a.save()

            return redirect('appointments:appointment_history')


    full_name = f"{request.user.first_name} {request.user.last_name}"
    return render(request, 'appointment.html', {'full_name': full_name, 'doctors': doctors})

# @login_required
def appointment_history(request):
    try:
        # Access the patient's profile using the related_name
        patient = request.user.patient_profile
        appointments = Appointment.objects.filter(patient=patient).order_by('-date', '-time')
    except AttributeError:
        # Handle the case where the user is not a patient
        appointments = []

    return render(request, 'appointment_history.html', {'appointments': appointments})


def doctor_appointments(request):
    appointments = Appointment.objects.filter(doctor=request.user.doctor).order_by('-date', '-time')

    if request.method == 'POST':
        # Update appointment status (Confirmed or Cancelled)
        appointment_id = request.POST.get('appointment_id')
        new_status = request.POST.get('status')
        appointment = Appointment.objects.get(id=appointment_id)
        appointment.status = new_status
        appointment.save()
        return redirect('appointments:doctor_appointments')

    return render(request, 'doctor_appointments.html', {'appointments': appointments})

# Edit Appointment View
def edit_appointment(request, appointment_id):
    appointment = get_object_or_404(Appointment, id=appointment_id)
    doctors = Doctor.objects.all()

    if request.method == 'POST':
        department_name = request.POST['d']
        doctor_name = request.POST['doc']
        date = request.POST['date']
        time = request.POST['time']
        phone = request.POST['phone']
        message = request.POST['message']

        selected_department = Department.objects.get(name=department_name)
        doc = Doctor.objects.get(id=doctor_name)

        appointment.department = selected_department
        appointment.doctor = doc
        appointment.date = date
        appointment.time = time
        appointment.phone_number = phone
        appointment.message = message
        appointment.save()

        return redirect('appointments:appointment_history')

    return render(request, 'edit_appointment.html', {
        'appointment': appointment,
        'doctors': doctors
    })

#delete appointment
def delete_appointment(request, appointment_id):
    appointment = get_object_or_404(Appointment, id=appointment_id)

    if request.method == 'POST':
        appointment.delete()
        return redirect('appointments:appointment_history')

    return render(request, 'delete_appointment.html', {'appointment': appointment})

hospital_management/doctors/views.py
from django.shortcuts import render, redirect
from doctors.models import Department,Doctor
from django.db.models import Q
from django.contrib.auth.hashers import make_password

def alldepartments(request):
    d=Department.objects.all()

    return render(request, 'department.html',{'dep':d})

def alldoctors(request,d):
    d = Department.objects.get(id=d)
    doc = Doctor.objects.filter(department=d)
    return render(request,'doctor.html',{'dep':d,'doctor':doc})

def doctorsdetails(request,d):
    doc=Doctor.objects.get(id=d)
    return render(request,'doctordetail.html',{'doctor':doc})

def service(request):
    return render(request,'service.html')

def add_department(request):
    if request.method=='POST':
        name= request.POST['n']
        desc=request.POST['d']
        image=request.FILES['i']

        k=Department.objects.create(name=name,description=desc,image=image)
        k.save()
        return redirect('doctors:department')
    return render(request,'add_department.html')

def edit_department(request, id):
    department = Department.objects.get(id=id)
    if request.method == 'POST':
        department.name = request.POST['n']
        department.description = request.POST['d']
        if 'i' in request.FILES:
            department.image = request.FILES['i']
        department.save()
        return redirect('doctors:department')
    return render(request, 'edit_department.html', {'department': department})

def delete_department(request, id):
    department = Department.objects.get(id=id)
    department.delete()
    return redirect('doctors:department')

def add_doctor(request):
    if request.method=='POST':
        name= request.POST['n']
        firstname = request.POST['f']
        lastname = request.POST['l']
        desc=request.POST['d']
        # password = request.POST['pw']
        image=request.FILES.get('i')
        email=request.POST['e']
        phone=request.POST['p']
        specialization = request.POST['s']
        department = request.POST['d']

        # Hash the password for security
        # hashed_password = make_password(password)

        d=Department.objects.get(name=department)
        doc=Doctor.objects.create(name=name,first_name=firstname,last_name=lastname,description=desc,image=image,email=email,phone_number=phone,specialization=specialization,department=d) #password=hashed_password
        doc.save()

        return redirect('doctors:department')
    return render(request, 'add_doctor.html')

def search_doctor(request):
    query=""
    d=None
    if request.method=="POST":
        query=request.POST['q']
        if query:
            d=Doctor.objects.filter(Q(name__icontains=query) | Q(description__icontains=query) | Q(specialization__icontains=query))

    return render(request,'doctor_search.html',{'doctor':d,'q':query})

hospital_management/templates/confirmation.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

{% endblock %}

hospital_management/templates/department.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<style>
/* Common pill button styles */
.btn-pill {
    border-radius: 50px;
    padding: 8px 20px;
    font-size: 14px;
    font-weight: bold;
    transition: background-color 0.3s ease, color 0.3s ease;
}

/* Edit button styles */
.btn-edit {
    background-color: #003C43;
    color: #ffffff;
    border: 2px solid #003C43;
}

.btn-edit:hover {
    background-color: #257180;
    color: #ffffff;
    border: 2px solid #257180;
}

/* Delete button styles */
.btn-delete {
    background-color: #257180;
    color: #ffffff;
    border: 2px solid #257180;
}

.btn-delete:hover {
    background-color: #003C43;
    color: #ffffff;
    border: 2px solid #003C43;
}
</style>


<!--banner image-->
<section class="banner">
	<div class="container">
		<div class="row">
			<div class="col-lg-6 col-md-12 col-xl-7">
				<div class="block">
					<div class="divider mb-3"></div>
					<span class="text-uppercase text-sm letter-spacing ">Total Health care solution</span>
					<h1 class="mb-3 mt-3">Your most trusted health partner</h1>

					<p class="mb-4 pr-5">"Your health, our priority — because a healthy tomorrow starts with care today."</p>
					<div class="btn-container ">
						<a href="{% url 'appointments:book_appointment'  %}" target="_blank" class="btn btn-main-2 btn-icon btn-round-full">Make appoinment <i class="icofont-simple-right ml-2  "></i></a>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>

<section class="features">
	<div class="container">
		<div class="row">
			<div class="col-lg-12">
				<div class="feature-block d-lg-flex">
					<div class="feature-item mb-5 mb-lg-0">
						<div class="feature-icon mb-4">
							<i class="icofont-surgeon-alt"></i>
						</div>
						<span>24 Hours Service</span>
						<h4 class="mb-3">Online Appoinment</h4>
						<p class="mb-4">Access round-the-clock support for any emergency. We practice family medicine to provide continuous and comprehensive care for you and your family’s health needs.
						</p>
						<a href="{% url 'appointments:book_appointment'  %}" class="btn btn-main btn-round-full">Make a appoinment</a>
					</div>

					<div class="feature-item mb-5 mb-lg-0">
						<div class="feature-icon mb-4">
							<i class="icofont-ui-clock"></i>
						</div>
						<span>Timing schedule</span>
						<h4 class="mb-3">Working Hours</h4>
						<ul class="w-hours list-unstyled">
							<li class="d-flex justify-content-between">Sun - Wed : <span>8:00 - 17:00</span></li>
							<li class="d-flex justify-content-between">Thu - Fri : <span>9:00 - 17:00</span></li>
							<li class="d-flex justify-content-between">Sat - sun : <span>10:00 - 17:00</span></li>
						</ul>
					</div>

					<div class="feature-item mb-5 mb-lg-0">
						<div class="feature-icon mb-4">
							<i class="icofont-support"></i>
						</div>
						<span>Emegency Cases</span>
						<h4 class="mb-3">94-00-233-130</h4>
						<p>We are available around the clock to assist with any emergency. Our approach is based on the principles of family medicine, ensuring comprehensive care for you and your loved ones. Reach out to us for immediate support in case of any urgent situation.</p>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>

<!--sevices-->
<section class="section about">
	<div class="container">
		<div class="row align-items-center">
			<div class="col-lg-4 col-sm-6">
				<div class="about-img">
					<img src="{% static 'images/about/med1.jpg' %}" alt="" class="img-fluid">
					<img src="{% static 'images/about/med.jpg' %}" alt="" class="img-fluid mt-4">
				</div>
			</div>
			<div class="col-lg-4 col-sm-6">
				<div class="about-img mt-4 mt-lg-0">
					<img src="{% static 'images/about/med2.jpg' %}" alt="" class="img-fluid">
				</div>
			</div>
			<div class="col-lg-4">
				<div class="about-content pl-4 mt-4 mt-lg-0">
					<h2 class="title-color">Personal care <br>& healthy living</h2>
					<p class="mt-4 mb-5">Dedicated to providing personalized care and promoting healthy living for a better, happier you.</p>

					<a href="{% url 'doctors:service' %}" class="btn btn-main-2 btn-round-full btn-icon">Services<i class="icofont-simple-right ml-3"></i></a>
				</div>
			</div>
		</div>
	</div>
</section>

<!--departments-->

<section class="section service-2">
	<div class="container">
		<div class="row justify-content-center">
			<div class="col-lg-7 text-center">
				<div class="section-title">
					<h2>Our Health Care Departments</h2>
					<div class="divider mx-auto my-4"></div>
					<p>Explore the specialized care we offer across our diverse departments, designed to address your unique health needs.</p>
				</div>
			</div>
		</div>

		<div class="row">
			{% for i in dep %}
			<div class="col-lg-4 col-md-6 ">
				<div class="department-block mb-5">
					<img src="{{i.image.url}}" alt="" class="img-fluid w-100">
					<div class="content">
						<h4 class="mt-4 mb-2 title-color">{{i.name}}</h4>
						<p class="mb-4">{{i.description}}</p>
						<a href="{% url 'doctors:doctor' i.id %}" class="read-more">Visit<i class="icofont-simple-right ml-2"></i></a>
						{% if user.is_admin == True %}
							<!-- Show Edit and Delete buttons for admin users -->
<!--							<div>-->
								<a href="{% url 'doctors:edit_department' i.id %}" class="btn btn-pill btn-edit">Edit</a>
								<a href="{% url 'doctors:delete_department' i.id %}" class="btn btn-pill btn-delete" onclick="return confirm('Are you sure you want to delete this department?');">Delete</a>

<!--							</div>-->
							{% endif %}
					</div>
				</div>
			</div>
			{% endfor %}
		</div>
	</div>
</section>



{% endblock %}

hospital_management/templates/doctor_prescriptions.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<style>
    .table th, .table td {
        vertical-align: middle;
        text-align: center;
    }

    .table thead th {
        font-weight: 700;
        text-transform: uppercase;
    }

    .table-hover tbody tr:hover {
        background-color: #f8f9fa;
    }

    .table tbody td {
        color: #6F8BA4;
        font-size: 14px;
    }

</style>

<section class="page-title bg-1">
  <div class="overlay"></div>
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="block text-center">
          <span class="text-white">View Prescriptions Details</span>
          <h1 class="text-capitalize mb-5 text-lg">Doctor's Prescriptions</h1>
        </div>
      </div>
    </div>
  </div>
</section>

<section class="section doctors">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-lg-8 text-center">
        <div class="section-title">
          <h2>Prescription History</h2>
          <div class="divider mx-auto my-4"></div>
          <p>View a detailed record of all the prescriptions provided to your patients. This section displays the necessary details regarding admission, revisit requirements, lab tests, medication instructions, and prescription dates.</p>
        </div>
      </div>
    </div>

    <div class="table-responsive">
      <table class="table table-striped table-hover">
        <thead style="background-color: #257180; color: white;">
          <tr>
            <th>Patient Name</th>
            <th>Admission Required</th>
            <th>Revisit Required</th>
            <th>Lab Tests</th>
            <th>Medication Details</th>
            <th>Dosage Instructions</th>
            <th>Prescription Date</th>
            <th>Payment Amount</th>
          </tr>
        </thead>
        <tbody>
          {% for prescription in prescriptions %}
          <tr>
            <td>{{ prescription.patient.first_name }} {{ prescription.patient.last_name }}</td>
            <td>{{ prescription.admission_required|yesno:"Yes,No" }}</td>
            <td>{{ prescription.revisit_required|yesno:"Yes,No" }}</td>
            <td>{{ prescription.lab_tests }}</td>
            <td>{{ prescription.medication_details }}</td>
            <td>{{ prescription.dosage_instructions }}</td>
            <td>{{ prescription.prescription_date|date:"Y-m-d" }}</td>
            <td>{{prescription.prescription_amount}}</td>
          </tr>
          {% empty %}
          <tr>
            <td colspan="8" class="text-center text-danger">No prescriptions found.</td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
</section>

{% endblock %}

hospital_management/templates/pharmacy_category.html
{% extends 'pharmacy_base.html' %}
{% load static %}

{% block content %}

<!--banner image-->
<section class="banner1">
	<div class="container">
		<div class="row">
			<div class="col-lg-6 col-md-12 col-xl-7">
				<div class="block">
					<div class="divider mb-3"></div>
					<span class="text-uppercase text-sm letter-spacing ">Total Health care solution</span>
					<h1 class="mb-3 mt-3">Your Trusted Pharmacy Partner</h1>

					<p class="mb-4 pr-5">"Your health is our priority — we provide quality medications and expert advice for a healthier tomorrow."</p>
					<div class="btn-container ">
						<a href="{% url 'appointments:book_appointment'  %}" target="_blank" class="btn btn-main-2 btn-icon btn-round-full">Make appoinment <i class="icofont-simple-right ml-2  "></i></a>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>

<section class="features">
	<div class="container">
		<div class="row">
			<div class="col-lg-12">
				<div class="feature-block d-lg-flex">
					<div class="feature-item mb-5 mb-lg-0">
						<div class="feature-icon mb-4">
							<i class="icofont-surgeon-alt"></i>
						</div>
						<span>24 Hours Service</span>
						<h4 class="mb-3">Online Appoinment</h4>
						<p class="mb-4">Access round-the-clock support for any emergency. We practice family medicine to provide continuous and comprehensive care for you and your family’s health needs.</p>
						<a href="{% url 'appointments:book_appointment'  %}" class="btn btn-main btn-round-full">Make a appoinment</a>
					</div>

					<div class="feature-item mb-5 mb-lg-0">
						<div class="feature-icon mb-4">
							<i class="icofont-ui-clock"></i>
						</div>
						<span>Timing schedule</span>
						<h4 class="mb-3">Working Hours</h4>
						<ul class="w-hours list-unstyled">
							<li class="d-flex justify-content-between">Sun - Wed : <span>8:00 - 17:00</span></li>
							<li class="d-flex justify-content-between">Thu - Fri : <span>9:00 - 17:00</span></li>
							<li class="d-flex justify-content-between">Sat - sun : <span>10:00 - 17:00</span></li>
						</ul>
					</div>

					<div class="feature-item mb-5 mb-lg-0">
						<div class="feature-icon mb-4">
							<i class="icofont-support"></i>
						</div>
						<span>Emergency Cases</span>
						<h4 class="mb-3">94-00-233-130</h4>
						<p>We are available around the clock to assist with any emergency. Our approach is based on the principles of family medicine, ensuring comprehensive care for you and your loved ones. Reach out to us for immediate support in case of any urgent situation.</p>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>

<!--sevices-->
<!--<section class="section about">-->
<!--	<div class="container">-->
<!--		<div class="row align-items-center">-->

<!--			<div class="col-lg-4">-->
<!--				<div class="about-content pl-4 mt-4 mt-lg-0">-->
<!--					<h2 class="title-color">Personal care <br>& healthy living</h2>-->
<!--					<p class="mt-4 mb-5">Dedicated to providing personalized care and promoting healthy living for a better, happier you.</p>-->


<!--				</div>-->
<!--			</div>-->
<!--		</div>-->
<!--	</div>-->
<!--</section>-->
<section class="section about">
    <div class="container">
        <div class="row align-items-center">
            <div class="col-lg-12 text-center">
                <div class="about-content pl-4 mt-4 mt-lg-0">
                    <h2 class="title-color">Quality Medications <br>& Expert Care</h2>
                    <p class="mt-4 mb-5">
						We are committed to providing you with the highest quality medications and expert pharmaceutical care for your well-being and peace of mind. Our knowledgeable pharmacists are here to guide you through your health journey, offering personalized advice and tailored solutions to meet your unique needs. Whether you are seeking over-the-counter remedies or prescription medications, we ensure that every product is carefully selected and of the highest standards. Your health is our top priority, and we strive to support you in achieving optimal wellness every day.
					</p>

                </div>
            </div>
        </div>
    </div>
</section>



<!--departments-->

<section class="section service-2">
	<div class="container">
		<div class="row justify-content-center">
			<div class="col-lg-7 text-center">
				<div class="section-title">
					<h2>Our Pharmacy's Exclusive Store</h2>
					<div class="divider mx-auto my-4"></div>
					<p>Discover the diverse range of medicines we offer, carefully categorized to meet your health needs. From over-the-counter treatments to prescription medications, our extensive selection ensures you have access to the right solutions for your well-being. Browse our categories for everything from pain relief to chronic condition management, all backed by expert advice and care.</p>
				</div>
			</div>
		</div>

		<div class="row">
			{% for i in cat %}
			<div class="col-lg-4 col-md-6 ">
				<div class="department-block mb-5">
					<img src="{{i.image.url}}" alt="" class="img-fluid w-100">
					<div class="content">
						<h4 class="mt-4 mb-2 title-color">{{i.name}}</h4>
						<p class="mb-4">{{i.description}}</p>
						<a href="{% url 'pharmacy:medicines' i.id %}" class="read-more">Medicine<i class="icofont-simple-right ml-2"></i></a>
						{% if user.is_admin == True %}


							<a href="{% url 'pharmacy:edit_category' i.id %}" class="read-more">Edit<i class="icofont-simple-right ml-2"></i></a>
							<a href="{% url 'pharmacy:delete_category' i.id %}" class="read-more">Delete<i class="icofont-simple-right ml-2"></i></a>
						{% endif %}

					</div>
				</div>
			</div>
			{% endfor %}
		</div>
	</div>
</section>



{% endblock %}

hospital_management/templates/pharmacy_confirm_delete.html
{% extends 'pharmacy_base.html' %}
{% load static %}

{% block content %}
<style>
  .btn-cancel {
  background-color: #257180;
  color: white;
  text-decoration: none;
  padding: 10px 20px;
  border-radius: 50px;
  display: inline-block;
  transition: background-color 0.3s ease;
}

.btn-cancel:hover {
  background-color: #003C43;
}

</style>

<section class="page-title bg-danger">
  <div class="overlay"></div>
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="block text-center">
          <span class="text-white">DELETE CATEGORY</span>
          <h1 class="text-capitalize mb-5 text-lg">Are You Sure?</h1>
        </div>
      </div>
    </div>
  </div>
</section>

<section class="section">
  <div class="container">
    <div class="row">
      <div class="col-lg-8 offset-lg-2">
        <div class="appoinment-wrap mt-5 pl-lg-5">
          <h2 class="mb-2 title-color">Confirm Deletion</h2>
          <p class="mb-4">You are about to delete the following category. Please confirm your action.</p>

          <div class="category-details">
            <h4 class="title-color">Category Name: {{ category.name }}</h4>
          </div>

          <form method="POST">
            {% csrf_token %}

            <div class="row">
              <div class="col-lg-12">
                <button type="submit" class="btn btn-danger btn-round-full">Yes, Delete</button>
                <a href="{% url 'pharmacy:category' %}" class="btn btn-cancel btn-round-full">Cancel</a>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock %}

hospital_management/templates/pharmacy_paymentstatus.html
{% extends 'pharmacy_base.html' %}
{% load static %}

{% block content %}
<style>
    .btn-custom {
        background-color: #257180;
        color: white;
        border: none;
        border-radius: 50px; /* Makes the button pill-shaped */
        padding: 10px 20px; /* Adjust padding for better appearance */
        transition: background-color 0.3s ease, transform 0.2s ease; /* Smooth transition effect */
    }

    .btn-custom:hover {
        background-color: #003C43;
        transform: scale(1.05); /* Slight scaling effect on hover */
    }
</style>

<!-- Payment Status Section -->
<section class="page-title bg-1">
  <div class="overlay"></div>
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="block text-center">
          <span class="text-white">Payment Status</span>
          <h1 class="text-capitalize mb-5 text-lg">Payment Status Update</h1>
        </div>
      </div>
    </div>
  </div>
</section>

<!-- Payment Result Section -->
<section class="section doctors">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-lg-6 text-center">
        <div class="section-title">
          {% if status == True %}
            <h3 class="text-success mb-4">
              <i class="fa-solid fa-check-circle"></i> Payment Successful
            </h3>
            <p class="text-muted">Your payment has been successfully processed. Thank you for your order!</p>
          {% else %}
            <h3 class="text-danger mb-4">
              <i class="fa-solid fa-times-circle"></i> Payment Failed
            </h3>
            <p class="text-muted">Something went wrong with the payment. Please try again.</p>
          {% endif %}
        </div>
        <!-- Optional button to go back or retry -->
        <div class="mt-4">
          <a href="{% url 'pharmacy:category' %}" class="btn btn-custom btn-lg">Go to Home</a>
        </div>
      </div>
    </div>
  </div>
</section>

{% endblock %}